import { Inter } from 'next/font/google'
import HeaderNav from '@/components/layout/HeaderNav'
import resetStyle from '@/components/style/Reset.module.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body style={{ backgroundColor: '#f5f5f5' }} className={`${inter.className} ${resetStyle.reset}`}>
        <HeaderNav />
        <div>{children}</div>
        <div style={{ display: 'flex', justifyContent: 'center', alignItems: 'center', height: '50px' }}>
          <p style={{ color: "gray" }}>Contribute to this blog software in <a href="https://github.com/siloneco/Telepapyrus" style={{ color: 'gray' }}>siloneco/Telepapyrus</a></p>
        </div>
      </body>
    </html>
  )
}
