name: Code Style Test
on:
  push:
    paths-ignore:
      - "**.md"
      - "renovate.json"
  pull_request:
    paths-ignore:
      - "**.md"
      - "renovate.json"

jobs:
  build-test:
    if: ${{ github.event_name != 'pull_request' || github.repository != github.event.pull_request.head.repo.full_name }}
    name: Code Style Test
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v7
      - uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6
        with:
          version: 11
          run_install: false
      - uses: actions/setup-node@v7
        with:
          node-version: 24.19.0
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - run: cp ./.github/workflows/test-data/.env.test ./.env.local

      - run: node --version
      - run: pnpm --version

      - run: pnpm install --frozen-lockfile

      - run: pnpm run lint
      - run: pnpm run eslint
      - run: pnpm run type-check
