name: Test with Jest
on:
  push:
    paths-ignore:
      - "**.md"
      - "renovate.json"
  pull_request:
    paths-ignore:
      - "**.md"
      - "renovate.json"

jobs:
  test:
    if: ${{ github.event_name != 'pull_request' || github.repository != github.event.pull_request.head.repo.full_name }}
    name: Test with Jest
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    services:
      mariadb:
        image: mariadb:11.8.8
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: passwd
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 9
          run_install: false
      - uses: actions/setup-node@v4
        with:
          node-version: 22.23.2
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - name: Check MySQL CLI existence
        id: check-mysql-cli
        uses: andstor/file-existence-action@558493d6c74bf472d87c84eab196434afc2fa029 # v3
        with:
          files: "/usr/bin/mysql"
      - name: Install MySQL CLI
        if: steps.check-mysql-cli.outputs.files_exists == 'false'
        run: sudo apt-get update && sudo apt-get -y install mysql-client

      - uses: corrupt952/actions-retry-command@3f634a8c767d6fdde08095e3c3c4d42aa2d79bb3 # v1.0.7
        with:
          command: 'mysql --protocol=tcp -h localhost --port 3306 -u root -ppasswd -e "$(cat ./.github/workflows/test-data/test-mariadb-setup.sql)"'
          working_directory: ${{ github.workspace }}
          max_attempts: 3
          retry_interval: 10

      - run: cp ./.github/workflows/test-data/.env.test ./.env.test.local

      - run: node --version
      - run: pnpm --version

      - run: pnpm install --frozen-lockfile

      - run: pnpm run test
